### ISSUE TITLE
How to apply color for paragraph section?

### ISSUE THREAD

**Issue by RabertD** [Upstarts/editor.js-kit-ios#28]
Am not able to set the color for paragraph text. It's always showing as black color. Can you quickly help me on this

**Comment by ivanglushko** [comment]
Hi thanks for reaching out. In order to change color just use styling in html format like so
`<span style=\"color: #26528c;\">Hello how are you?</span>`
Which would show a navy colored text.
<img width="347" alt="Screenshot 2023-07-04 at 01 29 32" src="https://github.com/Upstarts/editor.js-kit-ios/assets/36343782/a9e92d63-2037-446c-ac0f-7d2df1e7d6c0">
